triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: hi
states:
    first:
        component: meya.text
        properties:
            text: Hello, World! 💯
    second:
        component: meya.text
        properties:
            text: "The second thing."
    output_joke:
        component: joke